const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE);
const [base, source, output] = process.argv.slice(2);
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_EXECUTABLE, headless: true, chromiumSandbox: true, args: ['--host-resolver-rules=MAP docsify.test 127.0.0.1', '--no-proxy-server'] });
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const page = await context.newPage();
  page.setDefaultTimeout(6000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await page.goto(base);
    const sync = page.getByRole('button', { name: '立即同步', exact: true });
    await sync.waitFor();
    await page.waitForFunction(() => !document.querySelector('#sync-docs').disabled);
    await page.getByRole('button', { name: '接入项目', exact: true }).click();
    await page.getByLabel('文档目录路径').fill('/no-such-docsify-directory');
    await page.getByRole('button', { name: '接入并同步', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#manage-status').dataset.state === 'error');
    await page.getByLabel('文档目录路径').fill(source);
    await page.getByRole('button', { name: '接入并同步', exact: true }).click();
    await page.locator('.project-card-head').waitFor();
    assert.match(await page.locator('#manage-status').innerText(), /2.*文件/);
    await page.getByLabel('文档目录路径').fill(source);
    await page.getByRole('button', { name: '接入并同步', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#manage-status').dataset.state === 'error');
    assert.equal(await page.locator('.project-card-head').count(), 1);
    fs.writeFileSync(source + '/README.md', '# 浏览器同步验证\n\n更新后的原文。');
    fs.writeFileSync(source + '/new.md', '# 新增文档\n\n同步后应可搜索。');
    await sync.click();
    await page.waitForFunction(() => document.querySelector('#manage-status').dataset.state === 'success');
    assert.match(await page.locator('.project-detail').innerText(), /3/);
    await page.screenshot({ path: output + '/manage-desktop.png' });
    const projectHref = await page.locator('.project-card-head').getAttribute('href');
    await page.locator('.project-card-head').click();
    await page.waitForFunction(() => document.querySelector('.markdown-section h1')?.textContent.includes('浏览器同步验证'));
    await page.locator('.search input').fill('新增文档');
    await page.waitForFunction(() => document.querySelectorAll('.search .matching-post').length > 0);
    fs.unlinkSync(source + '/new.md');
    await page.goto(base);
    await page.waitForFunction(() => !document.querySelector('#sync-docs').disabled);
    await sync.click();
    await page.waitForFunction(() => document.querySelector('#manage-status').dataset.state === 'success');
    assert.equal(await page.evaluate(async url => (await fetch(url)).status, projectHref + 'content/new.md'), 404);
    assert.equal(await page.evaluate(async url => (await fetch(url)).status, projectHref + 'raw/.private.md'), 404);
    await page.setViewportSize({ width: 400, height: 850 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: output + '/manage-mobile.png' });
    await page.route(base + '/api/refresh', route => route.fulfill({ status: 502, contentType: 'text/html', body: '<h1>Bad Gateway</h1>' }));
    await sync.click();
    await page.waitForFunction(() => document.querySelector('#manage-status').dataset.state === 'error');
    assert.match(await page.locator('#manage-status').innerText(), /管理服务暂不可用/);
    await page.unroute(base + '/api/refresh');
    await page.route(base + '/api/**', route => route.abort());
    await page.reload();
    await page.waitForFunction(() => document.querySelector('#manage-status').dataset.state === 'error');
    assert.equal(await sync.isDisabled(), true);
    assert.equal(await page.locator('.project-card-head').count(), 1);
    assert.deepEqual(errors, []);
    console.log('通过：页面注册、重复/无效路径、增删改同步、阅读与搜索、手机布局、控制接口离线。');
  } finally {
    await context.close();
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
